name: Update Recent Activity
on:
  schedule:
    - cron: '0 */6 * * *'   # a cada 6h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_USERNAME: maedgomes
          COMMIT_MSG: "chore: atualizar atividades no README [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: [ main ]
    paths-ignore: [ 'README.md', 'docs/**' ]
  pull_request:
    paths-ignore: [ 'README.md', 'docs/**' ]
