name: Update Recent Activity

on:
  schedule:
    - cron: '0 */6 * * *'   # a cada 6 horas
  workflow_dispatch:        # botão para rodar manualmente
  push:
    branches: [ main ]      # se quiser rodar em push também
    paths-ignore:
      - 'README.md'         # não roda se mudar só o README

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_USERNAME: maedgomes
          COMMIT_MSG: "chore: atualizar atividades no README [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
